services:

  guzzle.http_client:
    class: GuzzleHttp\Client
    arguments: [{timeout: 10}]

  scenario.service:
    class: AppBundle\Service\ScenarioService
    calls:
        - ['setHttpClient', ["@guzzle.http_client"]]
        - ['setApiHostname', ["%api_hostname%"]]
        - ['setSettingsService', ["@settings.service"]]

  settings.service:
    class: AppBundle\Service\SettingsService
    calls:
        - ['setSession', ["@session"]]
