services:

  guzzle.http_client:
    class: GuzzleHttp\Client
    arguments: [{timeout: 5}]

  scenario.service:
    class: AppBundle\Service\ScenarioService
    calls:
        - ['setHttpClient', ["@guzzle.http_client"]]
        - ['setApiHostname', ["%api_hostname%"]]
